import { Language } from './types';

export const caseDescriptions: { [key: string]: { description: { [key: string]: string } } } = {
    'EXO024': {
        description: {
            es: "Solución protésica fija y atornillada para arcadas parciales o completas, fabricada en zirconio de alta translucidez para resultados estéticos excepcionales. Diseñado mediante tecnología CAD/CAM, este puente ofrece un ajuste preciso y pasivo, combinando una resistencia sobresaliente con una apariencia natural similar al diente. Es la opción ideal para el sector anterior, donde la estética es primordial, proporcionando al paciente una restauración duradera, biocompatible y de aspecto natural.",
            en: "A fixed, screw-retained prosthetic solution for partial or full arches, made of high-translucency zirconia for exceptional aesthetic results. Designed using CAD/CAM technology, this bridge offers a precise and passive fit, combining outstanding strength with a natural, tooth-like appearance. It is the ideal option for the anterior sector, where aesthetics are paramount, providing the patient with a durable, biocompatible, and natural-looking restoration.",
            pt: "Solução protética fixa e aparafusada para arcadas parciais ou completas, fabricada em zircónia de alta translucidez para resultados estéticos excecionais. Desenhada com tecnologia CAD/CAM, esta ponte oferece um ajuste preciso e passivo, combinando uma resistência notável com uma aparência natural semelhante à do dente. É a opção ideal para o setor anterior, onde a estética é primordial, proporcionando ao paciente uma restauração duradoura, biocompatível e de aspeto natural."
        }
    },
    'EXO025': {
        description: {
            es: "Estructura para puente sobre implantes, atornillada y de arcada completa, fresada con precisión a partir de un bloque de zirconio monolítico. Ofrece una resistencia y durabilidad excepcionales, siendo ideal para rehabilitaciones extensas tanto en el sector posterior como en arcadas completas. Su fabricación CAD/CAM garantiza un ajuste pasivo y preciso sobre los implantes, minimizando la tensión. Proporciona una base robusta y biocompatible para la cerámica de recubrimiento, asegurando una función y estética a largo plazo.",
            en: "A framework for a screw-retained, full-arch implant bridge, precision-milled from a monolithic zirconia block. It offers exceptional strength and durability, making it ideal for extensive rehabilitations in both the posterior sector and full arches. Its CAD/CAM manufacturing ensures a passive and precise fit on the implants, minimizing stress. It provides a robust and biocompatible base for veneering ceramic, ensuring long-term function and aesthetics.",
            pt: "Estrutura para ponte sobre implantes, aparafusada e de arcada completa, fresada com precisão a partir de um bloco de zircónia monolítica. Oferece resistência e durabilidade excecionais, sendo ideal para reabilitações extensas tanto no setor posterior como em arcadas completas. A sua fabricação CAD/CAM garante um ajuste passivo e preciso sobre os implantes, minimizando a tensão. Proporciona uma base robusta e biocompatível para a cerâmica de revestimento, assegurando função e estética a longo prazo."
        }
    },
    'EXO026': {
        description: {
            es: "Corona de zirconio de contorno completo (Full-Contour Zirconia), monolítica y atornillada, diseñada para restauraciones unitarias. Al estar fabricada en una sola pieza, elimina el riesgo de desprendimiento de la cerámica de recubrimiento (chipping). Indicada principalmente para el sector posterior por su extraordinaria resistencia a la fractura y al desgaste. Ofrece una solución eficiente, duradera y rentable, con una excelente biocompatibilidad y un protocolo clínico simplificado.",
            en: "A full-contour zirconia crown, monolithic and screw-retained, designed for single-unit restorations. Being made in one piece, it eliminates the risk of ceramic chipping. It is primarily indicated for the posterior sector due to its extraordinary fracture and wear resistance. It offers an efficient, durable, and cost-effective solution with excellent biocompatibility and a simplified clinical protocol.",
            pt: "Coroa de zircónia de contorno completo (Full-Contour Zirconia), monolítica e aparafusada, desenhada para restaurações unitárias. Por ser fabricada numa única peça, elimina o risco de lascamento da cerâmica de revestimento (chipping). Indicada principalmente para o setor posterior pela sua extraordinária resistência à fratura e ao desgaste. Oferece uma solução eficiente, duradoura e económica, com excelente biocompatibilidade e um protocolo clínico simplificado."
        }
    },
    'EXO028': {
        description: {
            es: "Pilar de titanio personalizado con canal de tornillo angulado (Angulated Screw Channel - ASC). Esta innovadora tecnología permite desviar el acceso del tornillo hasta 25 grados en un radio de 360°, optimizando la estética en restauraciones atornilladas, especialmente en la zona anterior, al evitar la salida del canal por la cara vestibular. Fabricado con tecnología CAD/CAM, se diseña a medida para un perfil de emergencia ideal, combinando la facilidad de extracción de una prótesis atornillada con la estética de una cementada.",
            en: "A customized titanium abutment with an Angulated Screw Channel (ASC). This innovative technology allows the screw access channel to be deflected up to 25 degrees within a 360° radius, optimizing aesthetics in screw-retained restorations, especially in the anterior zone, by avoiding the channel exit on the buccal face. Manufactured with CAD/CAM technology, it is custom-designed for an ideal emergence profile, combining the retrievability of a screw-retained prosthesis with the aesthetics of a cemented one.",
            pt: "Pilar de titânio personalizado com canal de parafuso angulado (Angulated Screw Channel - ASC). Esta tecnologia inovadora permite desviar o acesso do parafuso até 25 graus num raio de 360°, otimizando a estética em restaurações aparafusadas, especialmente na zona anterior, ao evitar a saída do canal pela face vestibular. Fabricado com tecnologia CAD/CAM, é desenhado à medida para um perfil de emergência ideal, combinando a facilidade de remoção de uma prótese aparafusada com a estética de uma cimentada."
        }
    },
    'EXO027': {
        description: {
            es: "Pilar de titanio individualizado, diseñado y fabricado mediante tecnología CAD/CAM para adaptarse a la anatomía específica del tejido blando de cada paciente. Proporciona un soporte óptimo y un perfil de emergencia ideal para la restauración final cementada. Fabricado en una aleación de titanio biocompatible, garantiza una alta precisión, resistencia y una base estable para coronas y puentes, contribuyendo a la salud periimplantaria y a resultados estéticos duraderos.",
            en: "An individualized titanium abutment, designed and manufactured using CAD/CAM technology to adapt to the specific soft tissue anatomy of each patient. It provides optimal support and an ideal emergence profile for the final cemented restoration. Made from a biocompatible titanium alloy, it ensures high precision, strength, and a stable base for crowns and bridges, contributing to peri-implant health and long-lasting aesthetic results.",
            pt: "Pilar de titânio individualizado, desenhado e fabricado com tecnologia CAD/CAM para se adaptar à anatomia específica do tecido mole de cada paciente. Proporciona um suporte ótimo e um perfil de emergência ideal para a restauração final cimentada. Fabricado numa liga de titânio biocompatível, garante alta precisão, resistência e uma base estável para coroas e pontes, contribuindo para a saúde peri-implantar e resultados estéticos duradouros."
        }
    },
    'EXO030': {
        description: {
            es: "Pilar personalizado fabricado en dióxido de zirconio, diseñado para ofrecer la máxima estética en restauraciones cementadas, especialmente en el sector anterior. Su color similar al diente evita el oscurecimiento del margen gingival, un aspecto crucial en pacientes con biotipos gingivales finos. Combina un cuerpo de zirconio con una base de conexión de titanio prefabricada, asegurando un ajuste preciso y fiable al implante. Es la solución ideal para resultados estéticos predecibles y naturales.",
            en: "A custom abutment made of zirconium dioxide, designed to offer maximum aesthetics in cemented restorations, especially in the anterior sector. Its tooth-like color prevents darkening of the gingival margin, a crucial aspect in patients with thin gingival biotypes. It combines a zirconia body with a prefabricated titanium connection base, ensuring a precise and reliable fit to the implant. It is the ideal solution for predictable and natural aesthetic results.",
            pt: "Pilar personalizado fabricado em dióxido de zircónio, desenhado para oferecer a máxima estética em restaurações cimentadas, especialmente no setor anterior. A sua cor semelhante à do dente evita o escurecimento da margem gengival, um aspeto crucial em pacientes com biótipos gengivais finos. Combina um corpo de zircónia com uma base de conexão de titânio pré-fabricada, assegurando um ajuste preciso e fiável ao implante. É a solução ideal para resultados estéticos previsíveis e naturais."
        }
    },
    'EXO029': {
        description: {
            es: "Estructura para puente sobre implantes, atornillada y de alta precisión, fresada a partir de un bloque sólido de titanio. Esta solución ofrece una resistencia y durabilidad excepcionales con un peso reducido, siendo ideal para rehabilitaciones de arcada completa. El diseño CAD/CAM garantiza un ajuste pasivo y sin tensiones sobre los implantes, un factor clave para el éxito a largo plazo. Sirve como subestructura robusta para el recubrimiento con resinas acrílicas o composite.",
            en: "A high-precision, screw-retained framework for an implant bridge, milled from a solid titanium block. This solution offers exceptional strength and durability with reduced weight, making it ideal for full-arch rehabilitations. The CAD/CAM design ensures a passive, tension-free fit on the implants, a key factor for long-term success. It serves as a robust substructure for veneering with acrylic resins or composite.",
            pt: "Estrutura para ponte sobre implantes, aparafusada e de alta precisão, fresada a partir de um bloco sólido de titânio. Esta solução oferece resistência e durabilidade excecionais com um peso reduzido, sendo ideal para reabilitações de arcada completa. O desenho CAD/CAM garante um ajuste passivo e sem tensões sobre os implantes, um fator chave para o sucesso a longo prazo. Serve como subestrutura robusta para o revestimento com resinas acrílicas ou compósito."
        }
    },
    'EXO031': {
        description: {
            es: "Estructuras y cofias de alta precisión para coronas y puentes cementados sobre dientes naturales o pilares de implantes. Fabricadas mediante el sistema CAD/CAM NobelProcera, están disponibles en materiales de alto rendimiento como el zirconio (para una estética superior) y el titanio (para una máxima resistencia). Garantizan un ajuste marginal excelente y una base de soporte homogénea para la cerámica de recubrimiento, ofreciendo restauraciones fiables y predecibles.",
            en: "High-precision frameworks and copings for cemented crowns and bridges on natural teeth or implant abutments. Manufactured using the NobelProcera CAD/CAM system, they are available in high-performance materials like zirconia (for superior aesthetics) and titanium (for maximum strength). They ensure excellent marginal fit and a homogeneous support base for the veneering ceramic, offering reliable and predictable restorations.",
            pt: "Estruturas e copings de alta precisão para coroas e pontes cimentadas sobre dentes naturais ou pilares de implantes. Fabricadas com o sistema CAD/CAM NobelProcera, estão disponíveis em materiais de alto desempenho como a zircónia (para uma estética superior) e o titânio (para máxima resistência). Garantem um ajuste marginal excelente e uma base de suporte homogénea para a cerâmica de revestimento, oferecendo restaurações fiáveis e previsíveis."
        }
    },
    'EXO032': {
        description: {
            es: "Barras sobre implantes fresadas con precisión a partir de un bloque de titanio sólido, diseñadas para la retención de sobredentaduras. Proporcionan una subestructura rígida y estable que mejora significativamente la retención, el soporte y la comodidad de la prótesis removible. El ajuste pasivo, garantizado por la fabricación CAD/CAM, distribuye las fuerzas de manera uniforme entre los implantes. Permiten la incorporación de diversos sistemas de ataches para una solución personalizada y funcional.",
            en: "Implant bars precision-milled from a solid titanium block, designed for overdenture retention. They provide a rigid and stable substructure that significantly improves the retention, support, and comfort of the removable prosthesis. The passive fit, guaranteed by CAD/CAM manufacturing, distributes forces evenly among the implants. They allow for the incorporation of various attachment systems for a customized and functional solution.",
            pt: "Barras sobre implantes fresadas com precisão a partir de um bloco sólido de titânio, desenhadas para a retenção de sobredentaduras. Proporcionam uma subestrutura rígida e estável que melhora significativamente a retenção, o suporte e o conforto da prótese removível. O ajuste passivo, garantido pela fabricação CAD/CAM, distribui as forças de maneira uniforme entre os implantes. Permitem a incorporação de diversos sistemas de attachments para uma solução personalizada e funcional."
        }
    },
    'EXO033': {
        description: {
            es: "Se trata de un Tornillo Protésico Temporal diseñado para Aditamentos Multi-unit de Nobel Biocare y es un componente diseñado para restauraciones temporales y muy especialmente para restauraciones impresas con resinas OnX.\n• Número de artículo 302502\n• Permite angular el acceso del tornillo\n• Requiere el destornillador Omnigrip Mini.\n• Disponible para plataformas NP, RP y WP\n• Composición Titanio",
            en: "This is a Temporary Prosthetic Screw designed for Nobel Biocare Multi-unit Abutments and is a component designed for temporary restorations, especially for printed restorations with OnX resins.\n• Article number 302502\n• Allows for angulated screw access\n• Requires the Omnigrip Mini screwdriver.\n• Available for NP, RP, and WP platforms\n• Composition: Titanium",
            pt: "Este é um Parafuso Protético Temporário concebido para Abutments Multi-unit da Nobel Biocare e é um componente concebido para restaurações temporárias, especialmente para restaurações impressas com resinas OnX.\n• Número de artigo 302502\n• Permite angular o acesso do parafuso\n• Requer a chave de fenda Omnigrip Mini.\n• Disponível para plataformas NP, RP e WP\n• Composição: Titânio"
        }
    },
    'EXO021': {
        description: {
            es: "Componente protésico de titanio que actúa como interfaz entre el implante y la restauración final en flujos de trabajo digitales. La versión no rotatoria (sin sistema antirrotacional) está indicada para restauraciones de múltiples unidades ferulizadas, como puentes, permitiendo un asentamiento pasivo de la estructura sobre varios implantes. Ofrece la precisión de una conexión original Nobel Biocare para laboratorios que utilizan sistemas CAD/CAM abiertos.",
            en: "A titanium prosthetic component that acts as an interface between the implant and the final restoration in digital workflows. The non-engaging version (without an anti-rotation system) is indicated for splinted multi-unit restorations, such as bridges, allowing for a passive fit of the structure over multiple implants. It offers the precision of an original Nobel Biocare connection for labs using open CAD/CAM systems.",
            pt: "Componente protético de titânio que atua como interface entre o implante e a restauração final em fluxos de trabalho digitais. A versão não rotacional (sem sistema anti-rotacional) é indicada para restaurações de múltiplas unidades ferulizadas, como pontes, permitindo um assentamento passivo da estrutura sobre vários implantes. Oferece a precisão de uma conexão original Nobel Biocare para laboratórios que utilizam sistemas CAD/CAM abertos."
        }
    },
    'EXO022': {
        description: {
            es: "Interfaz protésica de titanio para flujos de trabajo CAD/CAM, diseñada para restauraciones unitarias. La versión rotatoria incorpora un elemento antirrotacional (engaging) que se acopla con la conexión del implante, previniendo el giro de la corona. Permite a los laboratorios dentales diseñar y fresar pilares o coronas personalizadas sobre una base con la conexión original y garantizada de Nobel Biocare, asegurando un ajuste preciso y un rendimiento a largo plazo.",
            en: "A titanium prosthetic interface for CAD/CAM workflows, designed for single-unit restorations. The engaging version incorporates an anti-rotational element that couples with the implant connection, preventing crown rotation. It allows dental labs to design and mill custom abutments or crowns on a base with the original and guaranteed Nobel Biocare connection, ensuring a precise fit and long-term performance.",
            pt: "Interface protética de titânio para fluxos de trabalho CAD/CAM, desenhada para restaurações unitárias. A versão rotacional incorpora um elemento anti-rotacional (engaging) que se acopla à conexão do implante, prevenindo a rotação da coroa. Permite que os laboratórios dentários desenhem e fresem pilares ou coroas personalizadas sobre uma base com a conexão original e garantida da Nobel Biocare, assegurando um ajuste preciso e um desempenho a longo prazo."
        }
    },
    'EXO023': {
        description: {
            es: "El software DTX Clinic permite exportar al laboratorio la planificación realizada con el fin de ser importado en Exocad y de ese modo permite realizar un provisional, listo para ser capturado en boca después de la cirugía. Ver como",
            en: "The DTX Clinic software allows exporting the planning to the lab to be imported into Exocad, thus enabling the creation of a temporary restoration, ready to be captured in the mouth after surgery. See how",
            pt: "O software DTX Clinic permite exportar o planejamento realizado para o laboratório para ser importado no Exocad, permitindo assim a criação de uma restauração provisória, pronta para ser capturada na boca após a cirurgia. Ver como",
            fr: "Le logiciel DTX Clinic permet d'exporter la planification vers le laboratoire pour l'importer dans Exocad, permettant ainsi de créer une restauration provisoire, prête à être scannée en bouche après la chirurgie. Voir comment",
            sv: "DTX Clinic-programvaran gör det möjligt att exportera planeringen till labbet för import i Exocad, vilket möjliggör skapandet av en tillfällig restaurering, redo att fångas i munnen efter operationen. Se hur"
        }
    },
    'EXO013': {
        description: {
            es: "Componente protésico específico para el sistema de implantes Nobel Biocare N1. Esta base se cementa o adhiere a la Base N1, que se coloca en el implante, para facilitar un flujo de trabajo digital. Permite la fabricación de restauraciones personalizadas (pilares o coronas) utilizando sistemas CAD/CAM, manteniendo la integridad y precisión de la exclusiva conexión cónica trioval (TCC) del sistema N1.",
            en: "A prosthetic component specific to the Nobel Biocare N1 implant system. This base is cemented or bonded to the N1 Base, which is placed on the implant, to facilitate a digital workflow. It allows for the fabrication of custom restorations (abutments or crowns) using CAD/CAM systems, maintaining the integrity and precision of the unique tri-oval conical connection (TCC) of the N1 system.",
            pt: "Componente protético específico para o sistema de implantes Nobel Biocare N1. Esta base é cimentada ou colada à Base N1, que é colocada no implante, para facilitar um fluxo de trabalho digital. Permite a fabricação de restaurações personalizadas (pilares ou coroas) utilizando sistemas CAD/CAM, mantendo a integridade e precisão da exclusiva conexão cónica tri-oval (TCC) do sistema N1."
        }
    },
    'EXO006': {
        description: {
            es: "Interfaz protésica diseñada para el flujo de trabajo digital del sistema de implantes N1. Se conecta directamente a la Conexión Cónica Trioval (TCC) del implante N1, sirviendo como plataforma para la creación de restauraciones CAD/CAM. Asegura que la restauración final se beneficie de la estabilidad y el sellado de la conexión original N1, permitiendo a los laboratorios la flexibilidad de fabricar sus propias soluciones protésicas con una base fiable y precisa.",
            en: "A prosthetic interface designed for the digital workflow of the N1 implant system. It connects directly to the Tri-oval Conical Connection (TCC) of the N1 implant, serving as a platform for creating CAD/CAM restorations. It ensures the final restoration benefits from the stability and seal of the original N1 connection, allowing labs the flexibility to fabricate their own prosthetic solutions on a reliable and precise base.",
            pt: "Interface protética desenhada para o fluxo de trabalho digital do sistema de implantes N1. Conecta-se diretamente à Conexão Cónica Tri-oval (TCC) do implante N1, servindo como plataforma para a criação de restaurações CAD/CAM. Assegura que a restauração final beneficie da estabilidade e selagem da conexão original N1, permitindo aos laboratórios a flexibilidade de fabricar as suas próprias soluções protéticas com uma base fiável e precisa."
        }
    },
    'EXO019': {
        description: {
            es: "Componente clave del concepto On1™, diseñado para preservar los tejidos blandos periimplantarios. Esta base se conecta a la Base On1, que permanece en su sitio desde la cirugía, elevando la plataforma de trabajo a nivel tisular. Simplifica el proceso restaurador al evitar la manipulación de los tejidos blandos en las fases protésicas y permite la creación de restauraciones finales mediante un flujo digital, garantizando un ajuste preciso y la salud de los tejidos a largo plazo.",
            en: "A key component of the On1™ concept, designed to preserve peri-implant soft tissues. This base connects to the On1 Base, which remains in place from surgery, raising the working platform to the tissue level. It simplifies the restorative process by avoiding soft tissue manipulation in the prosthetic phases and allows for the creation of final restorations through a digital workflow, ensuring a precise fit and long-term tissue health.",
            pt: "Componente chave do conceito On1™, desenhado para preservar os tecidos moles peri-implantares. Esta base conecta-se à Base On1, que permanece no lugar desde a cirurgia, elevando a plataforma de trabalho ao nível do tecido. Simplifica o processo restaurador ao evitar a manipulação dos tecidos moles nas fases protéticas e permite a criação de restaurações finais através de um fluxo digital, garantindo um ajuste preciso e a saúde dos tecidos a longo prazo."
        }
    },
    'EXO020': {
        description: {
            es: "Pilar protésico diseñado específicamente para el implante cerámico de dos piezas NobelPearl. Fabricado en zirconio y fijado mediante un innovador tornillo de fibra de carbono Viccone®, ofrece una solución 100% libre de metal y de cemento. Este pilar asegura una estética excepcional gracias a su color natural y una excelente biocompatibilidad, siendo la opción ideal para pacientes con altas demandas estéticas o sensibilidad a los metales.",
            en: "A prosthetic abutment designed specifically for the two-piece NobelPearl ceramic implant. Made of zirconia and secured with an innovative Viccone® carbon fiber screw, it offers a 100% metal-free and cement-free solution. This abutment ensures exceptional aesthetics thanks to its natural color and excellent biocompatibility, making it the ideal choice for patients with high aesthetic demands or metal sensitivities.",
            pt: "Pilar protético desenhado especificamente para o implante cerâmico de duas peças NobelPearl. Fabricado em zircónia e fixado com um inovador parafuso de fibra de carbono Viccone®, oferece uma solução 100% livre de metal e de cimento. Este pilar assegura uma estética excecional graças à sua cor natural e excelente biocompatibilidade, sendo a opção ideal para pacientes com elevadas exigências estéticas ou sensibilidade a metais."
        }
    },
    'EXO016': {
        description: {
            es: "Bloque de titanio o cromo-cobalto prefabricado que incorpora una conexión original y garantizada de Nobel Biocare en su base. Está diseñado para laboratorios dentales con capacidad de fresado interno. Permite al laboratorio fresar la porción coronal del pilar de forma personalizada, combinando la flexibilidad y rapidez de la producción local con la seguridad y precisión de una conexión de implante genuina. Es una solución ideal para un flujo de trabajo digital abierto y eficiente.",
            en: "A prefabricated titanium or cobalt-chrome block that incorporates an original and guaranteed Nobel Biocare connection at its base. It is designed for dental labs with in-house milling capabilities. It allows the lab to custom-mill the coronal portion of the abutment, combining the flexibility and speed of local production with the security and precision of a genuine implant connection. It is an ideal solution for an open and efficient digital workflow.",
            pt: "Bloco de titânio ou cromo-cobalto pré-fabricado que incorpora uma conexão original e garantida da Nobel Biocare na sua base. É desenhado para laboratórios dentários com capacidade de fresagem interna. Permite ao laboratório fresar a porção coronal do pilar de forma personalizada, combinando a flexibilidade e rapidez da produção local com a segurança e precisão de uma conexão de implante genuína. É uma solução ideal para um fluxo de trabalho digital aberto e eficiente."
        }
    },
    'EXO014': {
        description: {
            es: "Pilar prefabricado de titanio diseñado para proporcionar resultados estéticos en restauraciones cementadas. Presenta un margen festoneado que imita el contorno natural de la encía, facilitando un perfil de emergencia estético. Como solución estándar, ofrece una opción eficiente y rentable para casos con anatomía gingival favorable, simplificando el procedimiento clínico en comparación con un pilar personalizado. Disponible en diferentes alturas y angulaciones para adaptarse a diversas situaciones clínicas.",
            en: "A prefabricated titanium abutment designed to provide aesthetic results in cemented restorations. It features a scalloped margin that mimics the natural gingival contour, facilitating an aesthetic emergence profile. As a standard solution, it offers an efficient and cost-effective option for cases with favorable gingival anatomy, simplifying the clinical procedure compared to a custom abutment. Available in different heights and angulations to adapt to various clinical situations.",
            pt: "Pilar pré-fabricado de titânio desenhado para proporcionar resultados estéticos em restaurações cimentadas. Apresenta uma margem festonada que imita o contorno natural da gengiva, facilitando um perfil de emergência estético. Como solução padrão, oferece uma opção eficiente e económica para casos com anatomia gengival favorável, simplificando o procedimento clínico em comparação com um pilar personalizado. Disponível em diferentes alturas e angulações para se adaptar a diversas situações clínicas."
        }
    },
    'EXO034': {
        description: {
            es: "Componente protésico fundamental para rehabilitaciones de arcada completa, como el concepto de tratamiento All-on-4®. Este pilar atornillado eleva la plataforma restauradora a nivel del tejido blando y permite corregir la angulación de los implantes inclinados. Simplifica drásticamente los procedimientos protésicos y el mantenimiento posterior, ya que la prótesis se fija a los pilares Multi-unit y no directamente a los implantes. Asegura un ajuste pasivo de la estructura y es la base para resultados predecibles y duraderos.",
            en: "A fundamental prosthetic component for full-arch rehabilitations, such as the All-on-4® treatment concept. This screw-retained abutment raises the restorative platform to the soft tissue level and allows for the correction of tilted implant angulation. It drastically simplifies prosthetic procedures and subsequent maintenance, as the prosthesis is fixed to the Multi-unit abutments and not directly to the implants. It ensures a passive fit of the framework and is the foundation for predictable and long-lasting results.",
            pt: "Componente protético fundamental para reabilitações de arcada completa, como o conceito de tratamento All-on-4®. Este pilar aparafusado eleva a plataforma restauradora ao nível do tecido mole e permite corrigir a angulação dos implantes inclinados. Simplifica drasticamente os procedimentos protéticos e a manutenção posterior, uma vez que a prótese é fixada aos pilares Multi-unit e não diretamente aos implantes. Assegura um ajuste passivo da estrutura e é a base para resultados previsíveis e duradouros."
        }
    },
    'EXO035': {
        description: {
            es: "Los pilares temporales de Nobel Biocare representan una pieza clave en el protocolo de tratamiento con implantes dentales, diseñados para ofrecer soluciones provisionales de alta calidad durante la fase de cicatrización y antes de la restauración definitiva. Estos componentes están orientados a mejorar los resultados estéticos y funcionales, así como la satisfacción del paciente, mediante la aplicación del probado concepto de Función Inmediata.",
            en: "Nobel Biocare temporary abutments are a key piece in the dental implant treatment protocol, designed to offer high-quality provisional solutions during the healing phase and before the final restoration. These components are aimed at improving aesthetic and functional outcomes, as well as patient satisfaction, through the application of the proven Immediate Function concept.",
            pt: "Os pilares temporários da Nobel Biocare representam uma peça fundamental no protocolo de tratamento com implantes dentários, concebidos para oferecer soluções provisórias de alta qualidade durante a fase de cicatrização e antes da restauração definitiva. Estes componentes visam melhorar os resultados estéticos e funcionais, bem como a satisfação do paciente, através da aplicação do comprovado conceito de Função Imediata."
        }
    }
};